### ISSUE TITLE
Action fails with `python-sigstore` error

### ISSUE THREAD

**Issue by mbestavros** [trailofbits/gh-action-sigstore-python#25]
Received this output from a run of the action (run linked [here](https://github.com/mbestavros/supply-chain-pipeline-demo/actions/runs/3063310998/jobs/4945242878):

```
❌ sigstore-python failed to sign package
❌ sigstore-python verification skipped due to failed signing
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/runpy.py", line 1[96](https://github.com/mbestavros/supply-chain-pipeline-demo/actions/runs/3063310998/jobs/4945242878#step:8:99), in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/sigstore/__main__.py", line 22, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/sigstore/_cli.py", line 257, in main
    _sign(args)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/sigstore/_cli.py", line 382, in _sign
    result = signer.sign(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/sigstore/_sign.py", line [101](https://github.com/mbestavros/supply-chain-pipeline-demo/actions/runs/3063310998/jobs/4945242878#step:8:104), in sign
    verify_sct(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/sigstore/_internal/sct.py", line 279, in verify_sct
    hash_algorithm, signature_algorithm, signature = _sct_properties(sct, raw_sct)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/sigstore/_internal/sct.py", line 82, in _sct_properties
    sct.hash_algorithm,  # type: ignore[attr-defined]
AttributeError: 'builtins.Sct' object has no attribute 'hash_algorithm'
```

Possibly a dependency error? I wasn't running into this issue before.

**Comment by mbestavros** [comment]
@woodruffw I was just drafting a PR to bump that, but it seems like it doesn't pass tests :sweat_smile:

**Comment by woodruffw** [comment]
Strange bug: the `ubuntu-latest` environment has `pyopenssl==19.0.0` installed, despite `sigstore` requesting `cryptography>=38` which should constrain `pyopenssl>=22.0.0`.

And yet, `pip` decides not to upgrade:

```
Requirement already satisfied: pyOpenSSL in /usr/lib/python3/dist-packages (from sigstore==0.6.4->-r /home/runner/work/gh-action-sigstore-python/gh-action-sigstore-python/.//requirements.txt (line 1)) (19.0.0)
```

This is a bug in `sigstore-python` itself, but I can patch around it for now and fix it upstream after a release here.

**Comment by mbestavros** [comment]
Thanks for the quick response and investigation!

**Comment by mbestavros** [comment]
Almost like making sure you have the right dependencies is important :eyes:

**Comment by woodruffw** [comment]
Okay, just tagged `v0.0.8` with the fix(es).

Let me know if that does the trick for you; we'll have another tagged release out when I get the `pyOpenSSL` constraint into `sigstore-python` itself.

And thanks again!

**Comment by mbestavros** [comment]
@woodruffw That worked! Thanks a bunch!
